Create the following Numpy array of 32-bit integers

    array([[1, 1, 1, 1, 1],
           [0, 1, 1, 1, 1],
           [0, 0, 1, 1, 1],
           [0, 0, 0, 1, 1],
           [0, 0, 0, 0, 1]])



In [1]:
import numpy as np

answer = np.triu(np.ones((5,5),np.int32))

In [2]:
print(answer)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


Create the following Numpy array of 16-bit integers

    array([[ 1,  2,  3,  4,  5],
           [ 0,  6,  7,  8,  9],
           [ 0,  0, 10, 11, 12],
           [ 0,  0,  0, 13, 14],
           [ 0,  0,  0,  0, 15]])

In [3]:
import numpy as np

answer = np.triu(np.ones((5,5),np.int16))
index = np.triu_indices(5)
element = []
for i in range(15):
    element.append(i + 1)
answer[index] = element

In [4]:
print(answer)

[[ 1  2  3  4  5]
 [ 0  6  7  8  9]
 [ 0  0 10 11 12]
 [ 0  0  0 13 14]
 [ 0  0  0  0 15]]


Given the following two-dimensional array, set the diagonal element to the average of the columns in each respective row not counting the diagonal element in each row. Note that the diagonal element itself is not part of the calculation. It is just a placeholder for the result.

    [[0,   3, 14, 13, 12],
     [13,  0,  8,  5, 11],
     [11, 11,  0, 12, 10],
     [11, 12,  1,  0, 10],
     [13, 12, 11,  4,  0]]
     
In this case, your answer should look like the following

    [[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
     [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
     [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
     [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
     [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]]

In the general case, the diagonal elements won't necessarily be equal to zero like they are here!

In [5]:
import numpy as np

def average_into_diagonal(x):
    '''
    return average of non-diagonal elements with values filled into the diagonal
    
    :param x: square two-dimensional input array
    :type x: numpy array
    :returns: numpy array

    '''
    assert isinstance(x,np.ndarray)
    assert x.ndim == 2
    assert x.shape[0] == x.shape[1] # square arrays only
    
    size = x.shape[0]
    diag = np.diag_indices(size)
    result = x.astype(np.float)
    result[diag] = 0
    rowAve = []
    for i in range(size):
        average = sum(result[i]) /(size - 1)
        rowAve.append(average)
    result[diag] = rowAve
    return result


In [6]:
x = np.array([[0,   3, 14, 13, 12],
 [13,  0,  8,  5, 11],
 [11, 11,  0, 12, 10],
 [11, 12,  1,  0, 10],
 [13, 12, 11,  4,  0]])
average_into_diagonal(x)

array([[ 10.5 ,   3.  ,  14.  ,  13.  ,  12.  ],
       [ 13.  ,   9.25,   8.  ,   5.  ,  11.  ],
       [ 11.  ,  11.  ,  11.  ,  12.  ,  10.  ],
       [ 11.  ,  12.  ,   1.  ,   8.5 ,  10.  ],
       [ 13.  ,  12.  ,  11.  ,   4.  ,  10.  ]])